@startuml
'https://plantuml.com/class-diagram

class Message{

    - String topic //消息所属topic
    - int flag //消息Flag
    - Map<String, String> properties //拓展属性
    note right
        Message拓展属性包含：
            tag: 消息TAG,用于消息过滤
            keys: Message索引键，多个用逗号隔开
            waitStoreMsgOK: 消息发送时是否等消息存储完成后再返回
            delayTimeLevel: 消息延迟级别，用于定时消息或消息重试
    end note
    - byte[] body //消息体
}

@enduml